---
version: '3'

services:
  db:
    image: postgres:13.4
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 6

  redis:
    image: redis:6.2.6
    restart: always
    command: redis-server --maxmemory-policy allkeys-lru --maxmemory 2G
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
